<a href="https://colab.research.google.com/github/anazzmuhmad/assessment-2/blob/main/numpy_pandas_assessment_Anaz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Section A

Q1

In [1]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]

In [2]:
arr.shape

(5,)

In [4]:
arr.dtype

dtype('int64')

Q2

In [5]:
arr = np.array([5,10,15,20,25])
print(arr + 5)

[10 15 20 25 30]

In [6]:
print(arr * 2)

[10 20 30 40 50]

Q3

In [7]:
arr = np.array([12, 15, 18, 20, 25, 30])
np.mean(arr)

np.float64(20.0)

In [8]:
np.median(arr)

np.float64(19.0)

In [9]:
np.min(arr)

np.int64(12)

In [10]:
np.max(arr)

np.int64(30)

In [11]:
np.std(arr)

np.float64(6.027713773341708)

Q4

In [12]:
arr = np.array([10, 25, 30, 45, 50, 65, 70])

arr[arr > 40]

array([45, 50, 65, 70])

Q5

In [17]:
import pandas as pd
df = pd.DataFrame({
    "Name" : ["Anu","Rahul","Meera","Arun"],
    "Age" : [21,22,20,23],
    "Score" : [85,72,91,68]
})
print(df)

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

Q6

In [15]:
df[["Name","Score"]]

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68

In [18]:
df[df["Name"] == "Meera"]

    Name  Age  Score
2  Meera   20     91

Q7

In [19]:
df[df["Score"] > 75]

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

Q8

In [20]:
df.shape

(4, 3)

In [21]:
df.columns

Index(['Name', 'Age', 'Score'], dtype='object')

In [22]:
df.dtypes

Name     object
Age       int64
Score     int64
dtype: object

In [23]:
df.describe()

             Age      Score
count   4.000000   4.000000
mean   21.500000  79.000000
std     1.290994  10.801234
min    20.000000  68.000000
25%    20.750000  71.000000
50%    21.500000  78.500000
75%    22.250000  86.500000
max    23.000000  91.000000

Q9

In [24]:
df.sort_values("Score", ascending = False)

    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

Q10

In [25]:
df = pd.DataFrame({
'Name': ['A', 'B', 'C', 'D'],
'Age': [21, np.nan, 23, 22],
'Score': [80, 75, np.nan, 90]
})
df

  Name   Age  Score
0    A  21.0   80.0
1    B   NaN   75.0
2    C  23.0    NaN
3    D  22.0   90.0

In [26]:
df.isnull()

    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [29]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
print(df["Age"])

0    21.0
1    22.0
2    23.0
3    22.0
Name: Age, dtype: float64

In [31]:
df["Score"] = df["Score"].fillna(df["Score"].mean())
print(df["Score"])

0    80.000000
1    75.000000
2    81.666667
3    90.000000
Name: Score, dtype: float64

In [32]:
df

  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000

Section B

Q11

In [33]:
import pandas as pd
student = pd.read_csv("/content/drive/MyDrive/DSA/Datasets/student_performance.csv")
student.head(5)

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9

In [34]:
student.tail(5)

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

In [35]:
student.shape

(80, 11)

In [36]:
student.columns

Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score',
       'Final_Score'],
      dtype='object')

In [37]:
student.dtypes

Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

In [38]:
student.describe()

,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
count,77.000000,77.000000,78.000000,80.000000,78.000000,78.000000,78.000000
mean,22.012987,81.672727,72.821795,70.445000,70.365385,68.574359,70.696154
std,2.155126,10.054204,16.722103,14.630417,15.814294,16.417242,14.053871
min,19.000000,56.300000,39.500000,38.300000,25.000000,25.000000,40.600000
25%,20.000000,75.500000,64.525000,60.650000,61.800000,57.175000,60.450000
50%,22.000000,81.100000,72.000000,69.300000,70.000000,70.700000,70.950000
75%,24.000000,86.400000,86.525000,81.150000,82.575000,80.650000,82.275000
max,25.000000,100.000000,100.000000,100.000000,100.000000,100.000000,97.000000

Q12

In [39]:
student[student["Final_Score"] > 75]

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
7,STU1008,Akhil Varma,Male,Computer Science,20.0,81.1,72.1,80.4,72.9,73.5,79.2
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1
17,STU1018,Priya Nair,Male,Data Science,19.0,85.4,62.6,81.6,79.6,75.5,75.1
23,STU1024,Fathima Joseph,Female,Commerce,23.0,78.2,87.7,71.0,88.5,74.8,83.7
24,STU1025,Kiran Varma,Female,Electronics,21.0,80.7,87.5,67.1,84.5,96.1,77.3
27,STU1028,Nikhil Nair,Female,Data Science,24.0,79.3,70.3,82.0,64.4,72.8,77.1
30,STU1031,Amal Varma,Female,Computer Science,19.0,86.7,86.9,64.3,100.0,89.2,85.5
33,STU1034,Amal Das,Male,Computer Science,19.0,85.5,94.4,81.6,71.3,81.5,84.3
35,STU1036,Maya Menon,Female,Electronics,19.0,82.0,95.3,93.4,100.0,62.5,84.2
37,STU1038,Kiran Pillai,Female,Electronics,25.0,85.2,87.8,78.3,85.5,82.7,82.4
39,STU1040,Rohan Sharma,Female,Computer Science,21.0,100.0,68.9,79.8,66.1,66.4,78.5
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5
41,STU1042,Arun Joseph,Female,Computer Science,21.0,85.9,71.2,76.1,70.8,NaN,77.9
43,STU1044,Rahul Das,Female,Computer Science,22.0,70.9,68.0,67.3,83.6,76.7,77.3
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
51,STU1052,Gokul Nair,Female,Commerce,25.0,77.3,80.4,85.3,96.7,83.5,79.3
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
56,STU1057,Rohan Pillai,Female,Commerce,20.0,79.5,72.1,66.9,61.8,72.3,75.2
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3
58,STU1059,Anu Menon,Male,Electronics,24.0,96.7,99.7,77.1,68.9,89.7,84.9
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0
64,STU1065,Rohan Sharma,Male,Computer Science,19.0,64.4,96.5,69.3,86.7,80.7,83.5
67,STU1068,Maya Das,Female,Computer Science,23.0,66.7,83.4,79.6,89.3,83.6,83.7
73,STU1074,Anu Kumar,Female,Computer Science,22.0,95.0,95.3,67.7,92.4,81.4,83.4
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

In [40]:
student[student["Attendance"] < 75]

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
9,STU1010,Gokul Pillai,Female,Computer Science,19.0,67.3,79.6,85.0,74.1,80.5,73.8
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9
15,STU1016,Nikhil Kumar,Female,Computer Science,NaN,70.3,55.9,69.3,67.1,58.4,58.2
19,STU1020,Vivek Sharma,Female,Commerce,22.0,72.1,65.8,60.9,49.8,44.8,54.6
25,STU1026,Maya Menon,Male,Electronics,20.0,68.3,91.7,64.5,83.5,73.7,69.4
36,STU1037,Nikhil Menon,Male,Electronics,22.0,74.8,69.5,60.7,64.6,81.6,69.1
42,STU1043,Sneha Varma,female,Data Science,19.0,74.4,71.8,79.1,69.8,95.9,NaN
43,STU1044,Rahul Das,Female,Computer Science,22.0,70.9,68.0,67.3,83.6,76.7,77.3
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3
50,STU1051,Gokul Menon,Male,Data Science,25.0,70.9,68.6,81.0,64.0,63.0,70.5
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9
64,STU1065,Rohan Sharma,Male,Computer Science,19.0,64.4,96.5,69.3,86.7,80.7,83.5
67,STU1068,Maya Das,Female,Computer Science,23.0,66.7,83.4,79.6,89.3,83.6,83.7
71,STU1072,Vivek Pillai,Male,Commerce,24.0,71.5,59.0,58.2,56.3,48.9,56.6

In [41]:
student[
    (student["Department"] == "Data Science") &
    (student["Final_Score"] > 80)
]

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9

In [43]:
student.sort_values("Final_Score",ascending = False)

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3
...,...,...,...,...,...,...,...,...,...,...,...
34,STU1035,Rahul Pillai,Female,Data Science,22.0,82.5,41.4,44.4,53.8,43.2,44.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
26,STU1027,Aditya Pillai,Female,Computer Science,25.0,79.6,44.0,52.5,25.0,25.0,40.6
42,STU1043,Sneha Varma,female,Data Science,19.0,74.4,71.8,79.1,69.8,95.9,NaN
53,STU1054,Maya Sharma,Male,Data Science,19.0,82.5,59.7,60.5,65.8,73.3,NaN

Q13

In [44]:
student["Average_Technical_Score"] = student[
    [
        "Python_Score",
        "SQL_Score",
        "Pandas_Score",
        "NumPy_Score"
    ]
].mean(axis=1)

In [45]:
student["Performance"] = np.select(
    [ student["Average_Technical_Score"] >= 90,
        student["Average_Technical_Score"] >= 75,
        student["Average_Technical_Score"] >= 60 ],
    [ "Excellent",
        "Good",
        "Average" ],
    default = "Needs Improvement"
)

In [48]:
student.head(80)

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3,65.200,Average
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1,73.400,Average
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2,54.475,Needs Improvement
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2,47.775,Needs Improvement
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5,46.525,Needs Improvement
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4,61.350,Average
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6,77.075,Good

Q14

In [57]:
department_result = student.groupby("Department").agg(
    Number_of_Students=("Student_ID", "count"),
    Average_Final_Score=("Final_Score", "mean"),
    Maximum_Final_Score=("Final_Score", "max"),
    Minimum_Final_Score=("Final_Score", "min")
)

department_result = department_result.sort_values(
    "Average_Final_Score",
    ascending=False
)
department_result.round(2)

,Number_of_Students,Average_Final_Score,Maximum_Final_Score,Minimum_Final_Score
Department,,,,
Electronics,13,72.85,86.9,51.2
Computer Science,29,71.48,96.0,40.6
Data Science,27,71.32,97.0,43.5
Commerce,8,67.82,83.7,54.6
data science,1,66.90,66.9,66.9
Data Science,1,55.10,55.1,55.1
Computer science,1,46.70,46.7,46.7

Q15

In [58]:
final_scores = student["Final_Score"].dropna().to_numpy()

In [59]:
np.mean(final_scores)

np.float64(70.69615384615383)

In [60]:
np.median(final_scores)

np.float64(70.95)

In [61]:
np.std(final_scores)

np.float64(13.96349124578818)

In [62]:
np.percentile(final_scores, 25)

np.float64(60.449999999999996)

In [63]:
np.percentile(final_scores, 75)

np.float64(82.275)

In [65]:
mean_score = np.mean(final_scores)
student[student["Final_Score"] > mean_score][
    ["Student_ID", "Name", "Final_Score"]
    ]

   Student_ID            Name  Final_Score
0     STU1001     Rahul Varma         82.7
4     STU1005       Asha Nair         81.9
6     STU1007     Akhil Varma         77.0
7     STU1008     Akhil Varma         79.2
8     STU1009      Diya Menon         83.0
9     STU1010    Gokul Pillai         73.8
10    STU1011        Diya Das         91.9
11    STU1012      Arun Reddy         86.9
16    STU1017    Rahul Thomas         91.1
17    STU1018      Priya Nair         75.1
20    STU1021      Arun Varma         73.2
23    STU1024  Fathima Joseph         83.7
24    STU1025     Kiran Varma         77.3
27    STU1028     Nikhil Nair         77.1
30    STU1031      Amal Varma         85.5
33    STU1034        Amal Das         84.3
35    STU1036      Maya Menon         84.2
37    STU1038    Kiran Pillai         82.4
39    STU1040    Rohan Sharma         78.5
40    STU1041     Amal Pillai         94.5
41    STU1042     Arun Joseph         77.9
43    STU1044       Rahul Das         77.3
46    STU1047       Gokul Das         74.8
47    STU1048     Priya Kumar         77.3
48    STU1049     Asha Sharma         97.0
51    STU1052      Gokul Nair         79.3
52    STU1053      Maya Varma         71.0
55    STU1056     Vivek Varma         93.3
56    STU1057    Rohan Pillai         75.2
57    STU1058     Diya Thomas         92.3
58    STU1059       Anu Menon         84.9
59    STU1060      Asha Menon         87.9
60    STU1061  Fathima Sharma         70.8
61    STU1062    Kiran Pillai         96.0
64    STU1065    Rohan Sharma         83.5
66    STU1067    Rahul Thomas         70.7
67    STU1068        Maya Das         83.7
72    STU1073   Swathi Joseph         73.5
73    STU1074       Anu Kumar         83.4
74    STU1075      Gokul Nair         70.9
77    STU1078  Fathima Sharma         75.2
79    STU1080      Diya Varma         78.6

Section C

Q16

A

In [66]:
student.isnull().sum()

Student_ID                 0
Name                       0
Gender                     0
Department                 0
Age                        3
Attendance                 3
Python_Score               2
SQL_Score                  0
Pandas_Score               2
NumPy_Score                2
Final_Score                2
Average_Technical_Score    0
Performance                0
dtype: int64

In [67]:
columns = [
    "Age",
    "Attendance",
    "Python_Score",
    "SQL_Score",
    "Pandas_Score",
    "NumPy_Score",
    "Final_Score"
]

for column in columns:
    student[column] = student[column].fillna(
        student[column].mean()
    )

B

In [68]:
student["Average_Score"] = student[
    [
        "Python_Score",
        "SQL_Score",
        "Pandas_Score",
        "NumPy_Score"
    ]
].mean(axis=1)

In [69]:
student["Pass_Status"] = np.where(
    student["Average_Score"] >= 50,
    "Pass",
    "Fail"
)

C

In [70]:
student.sort_values(
    "Average_Score",
    ascending=False
).head(5)[
    ["Student_ID", "Name", "Average_Score"]
]

   Student_ID          Name  Average_Score
10    STU1011      Diya Das         95.625
61    STU1062  Kiran Pillai         95.200
8     STU1009    Diya Menon         92.125
16    STU1017  Rahul Thomas         89.350
35    STU1036    Maya Menon         87.800

In [71]:
student.groupby(
    "Department"
)["Average_Score"].mean().sort_values(
    ascending=False
)

Department
Electronics         74.063462
Data Science        70.671783
Computer Science    70.515296
Commerce            68.806931
data science        64.725000
 Data Science       59.200000
Computer science    53.843590
Name: Average_Score, dtype: float64

In [72]:
student.groupby(
    "Department"
)["Attendance"].mean().round(2)

Department
 Data Science       76.70
Commerce            77.44
Computer Science    82.77
Computer science    92.10
Data Science        82.08
Electronics         80.58
data science        81.67
Name: Attendance, dtype: float64

In [73]:
student["Pass_Status"].value_counts()

Pass_Status
Pass    72
Fail     8
Name: count, dtype: int64

D

In [74]:
summary = student.groupby(
    "Department"
).agg(
    Total_Students=("Student_ID", "count"),
    Average_Score=("Average_Score", "mean"),
    Average_Attendance=("Attendance", "mean"),
    Pass_Count=("Pass_Status", lambda x: (x == "Pass").sum()),
    Fail_Count=("Pass_Status", lambda x: (x == "Fail").sum())
).reset_index()

summary = summary.round(2)

summary

,Department,Total_Students,Average_Score,Average_Attendance,Pass_Count,Fail_Count
0,Data Science,1,59.20,76.70,1,0
1,Commerce,8,68.81,77.44,8,0
2,Computer Science,29,70.52,82.77,24,5
3,Computer science,1,53.84,92.10,1,0
4,Data Science,27,70.67,82.08,24,3
5,Electronics,13,74.06,80.58,13,0
6,data science,1,64.72,81.67,1,0